FallDamage binder
Paradigm-Shift-Games/Voltz pull request #24
Opened 2022-08-01 20:23 UTC by planetme

Created handler for fall damage and added a config to scale fall damage and height threshold for damage.

2022-08-01 20:57 UTC, Hexcede commented
I'd probably rename the `Fall` config to `FallDamage` to match the binder

2022-08-01 22:04 UTC, 4812571 requested changes

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +local Config = require(ReplicatedStorage.Common.Config.FallDamage)
Rename this to FallDamageConfig

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +			signal:Fire(initialHeight - character.HumanoidRootPart.Position.Y)
What happened here?

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +    if fallHeight < Config.threshold then return else
Turn this into a guard clause.

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +    self.Health = self._humanoid.Health
Why is health public?

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Common/Config/FallDamage.lua
> +return {
Explicitly type local FallDamageConfig = {

}

2022-08-01 22:04 UTC, 4812571 commented on .vscode/settings.json
> +        "undefined-type"
Why did you disable this LSP setting?

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +function FallDamage:_detectFallHeight(character: Model, humanoid: Humanoid, signal: Signal)
Is this typedef for ``Signal`` correct?

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +    self._humanoid = self._character:WaitForChild("Humanoid")
Is it necessary for these variables to be in self?

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +    self:_detectFallHeight(self._character, self._humanoid, self._fallSignal)
Why are you passing the the fall Signal if it's in self already?

2022-08-01 22:04 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +    humanoid.FreeFalling:Connect(function(active)
This is a memory leak! Use Trove connect!

2022-08-01 22:09 UTC, 4812571 requested changes

2022-08-01 22:09 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +	local self = setmetatable({}, FallDamage)
What happened here?

2022-08-02 00:23 UTC, 4812571 requested changes

2022-08-02 00:23 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +    humanoid.Health -= damage
This should use humanoid:TakeDamage

2022-08-02 00:23 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +			self._fallSignal:Fire(initialHeight - character.HumanoidRootPart.Position.Y)
whitespace issue

2022-08-02 00:23 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +    self._trove:Connect(self._fallSignal, function(fallHeight) self:_updateHealth(fallHeight, humanoid) end)
self:_updateHealth can be moved into the detection code and thus the signal can be removed. Additionally, 'detectFallHeight' implies that the check happens once, try renamining it to something like 'trackCharacterFall' or something more descriptive and correct.

2022-08-02 06:05 UTC, 4812571 requested changes

2022-08-02 06:05 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +			fallHeight = initialHeight - character.HumanoidRootPart.Position.Y
Something wacky is happening here with whitespace. Try converting spaces to tabs first.

2022-08-02 06:05 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +            return
Move this into FallDamage:_updateHealth

2022-08-02 06:12 UTC, 4812571 requested changes

2022-08-02 06:12 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +            return
This return can be eliminated

2022-08-02 06:12 UTC, 4812571 commented on src/ReplicatedStorage/Client/InstanceComponents/Misc/FallDamage.lua
> +	self:_trackCharacterFall(character, humanoid)
Whitespace issue, try converting spaces to tabs

2022-08-02 06:12 UTC, nottirb commented
I would recommend changing spaces to tabs. You have a mix of both.

2022-08-02 06:18 UTC, nottirb commented on src/ServerScriptService/InstanceComponents/Misc/Character.lua
> +	CollectionService:AddTag(instance, "FallDamage")
The fall damage tag doesn't make sense to be under the "CameraLook tag" comment block. I would recommend changing the comment to read "Add character tags" or something of the sort.

2022-08-02 06:18 UTC, nottirb commented on src/ServerScriptService/InstanceComponents/Misc/Character.lua
> +	CollectionService:AddTag(instance, "FallDamage")
``Add tags to the character`` might be better wording.

2022-08-02 06:21 UTC, 4812571 approved these changes

2022-08-02 06:22 UTC, 4812571 commented
LGTM!

2022-08-02 06:22 UTC, merged