Basic observer
Paradigm-Shift-Games/Voltz pull request #53
Opened 2022-08-14 19:03 UTC by alfiebgtbhgh

PR: Added Basic Observer

2022-08-14 19:12 UTC, 4812571 requested changes
Hey, a few changes are needed.

2022-08-14 19:12 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +	return self
Many weird things have happened with your indentation here. Sometimes this is caused by tab/space mismatch. If it looks normal in your editor, run 'convert tabs to spaces' from the command bar - That usually resolves it for most people.

2022-08-14 19:12 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +            end
This could probably be using an if statement

2022-08-14 19:12 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +local MinimumRange = Settings.MinimumRange
Does this need to be imported? It seems like a bit of a micro-optimization

2022-08-14 19:12 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +local Settings = require(ReplicatedStorage.Common.Config.Terrain)
All of the other code uses 'StructureNameConfig' for this variable, so it should probably be 'ObserverConfig'

2022-08-14 19:12 UTC, 4812571 commented on src/ReplicatedStorage/Common/Config/Structures/Observer.lua
> +	MinimumRange = 20;
Couldn't this be called 'Range' instead of 'MinimumRange' for concision

2022-08-14 19:12 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +    RunService.Heartbeat:Connect(function()
There's a memory leak here! This connection will persist after the observer is destroyed!

2022-08-14 21:25 UTC, 4812571 requested changes
This didn't really address any of the issues with the PR - if you have any questions, you can always ask them in the comments.

2022-08-14 21:25 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +    RunService.Heartbeat:Connect(function()
You haven't resolved the memory leak. You're still leaking the table and the connection. The function is still being called every heatbeat.

2022-08-14 21:25 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +        for _,v in pairs(Players:GetPlayers()) do
There's almost never a case where a space after a comma could not improve readability.

2022-08-14 21:25 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +            end
This would probably be cleaner if it used an if expression. 

Luau reference: https://luau-lang.org/syntax#if-then-else-expressions

2022-08-14 21:25 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +	return self
There's still inconsistent whitespace throughout this PR - did you try to resolve it?

2022-08-14 22:48 UTC, Luke0x22918 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +            if not v.Character then return end
The loop would stop running for all players, if the character of one is nil. This can be fixed by using `continue` instead of `return`

2022-08-15 01:56 UTC, Olhado333 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +---@diagnostic disable-next-line: undefined-global
Why is this diagnostic disabled?

2022-08-15 01:56 UTC, Olhado333 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +local Range = ObserverConfig.Range
Why are you destructuring this config?

2022-08-15 01:56 UTC, Olhado333 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +end
The body of this function is empty, usually this is where we clean up memory. Observer uses a heartbeat connection, so memory cleanup is necessary.

2022-08-15 18:08 UTC, 4812571 requested changes

2022-08-15 18:08 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +---@diagnostic disable-next-line: undefined-global
I don't see any undefined globals in this file. Maybe this one slipped through?

2022-08-15 18:08 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +local Range = ObserverConfig.Range
Destructuring here saves a very miniscule amount of performance - at the cost of increased complexity. I don't think it's really a useful technique here.

2022-08-15 18:08 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +    RunService.Heartbeat:Connect(function()
This still leaks memory. While the function is no longer doing any effective work, it still has to check if ``self.Instance`` is nil or not every time ``RunService.Heartbeat`` fires. Additionally, the connection persists in memory, so the game's running memory will increase permanently every time an observer is built. The connection will hold a reference to the function being connected, and that function holds a reference to all variables indexed within it, so this code leaks the connection, the function, and the ``self`` table. These all need to be addressed by disconnecting the connection - as a general rule, if you connect to a 

[Signal:Connect()](https://developer.roblox.com/en-us/api-reference/datatype/RBXScriptSignal) returns a [Connection](https://developer.roblox.com/en-us/api-reference/datatype/RBXScriptConnection). You need to explicitly store this connection and call [Connect:Disconnect](https://developer.roblox.com/en-us/api-reference/datatype/RBXScriptSignal): to free the connection.

2022-08-15 18:08 UTC, 4812571 commented on src/ServerScriptService/InstanceComponents/Structures/Observer.lua
> +return Observer
We need to meet about these whitespace issues. Something is going wrong with your editor.

2022-08-15 18:24 UTC, 4812571 approved these changes
LGTM!

2022-08-15 18:24 UTC, merged